version: 2.1

orbs:
  python: circleci/python@2.1.1
  azure-acr: circleci/azure-acr@0.2.1

jobs:
  pull-and-test:
  description: "Setup Django application and run tests"
  executor: python/default
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: "Run tests"
        command: pytest -v

workflows:
  deploy-docker-image:
  jobs:
    - pull-and-test
    - azure-acr/build-and-push-image:
        login-server-name: flaskdockerflaskdemo.azurecr.io
        registry-name: flaskdockerflaskdemo
        repo: flask-rates-api
        requires:
          - pull-and-test
